dist: bionic
language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
- 'pypy3'
before_install:
  - pip install "pip==21.1.1"
  - pip install pipenv
install:
  - pipenv install --dev
script:
  - pipenv run nosetests  --with-coverage --cover-package=lob
after_success:
  - coveralls
notifications:
  slack:
    secure: aqg9JtvfexP2x6v9wicCfW2TSB9pFGOLFsuRTlkKM2HFfIM3O7YXX1nd3x7bwm7xuIXpBEDjqE9ImI4aM14k/ckkT3sS1GwZJuraV8zbkN3sAF1Zb3zgtXgb+jkt+hYITFjK5xPaaY3wd8+IJRna29tgxBhd9Yce7mQFQu5KbF4=
